name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: CPP-VS2015/
      run: docker build . --file Dockerfile --tag vs2022-vc140:$(date +%s)
